project_id = "rshmjqidfzemwxrlgcbr"

[functions.admin-user-management]
verify_jwt = false

[functions.auto-scheduler]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-event-notification]
verify_jwt = false

[functions.send-swap-notification]
verify_jwt = false

[functions.validate-invite-token]
verify_jwt = false

[functions.mark-invite-used]
verify_jwt = false

[functions.accept-swap-request]
verify_jwt = false

[functions.admin-accept-swap]
verify_jwt = false

[functions.send-assignment-removal-notification]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false

[functions.send-invitations]
verify_jwt = false

[functions.respond-invitation]
verify_jwt = false
