// This file is automatically generated. Do not edit it directly.
// Exception: `storage` is deliberately routed through createSafeStorage() so a
// browser that blocks storage cannot crash the bundle. Keep that if regenerated.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSafeLock, createSafeStorage } from './safeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeStorage(),
    lock: createSafeLock(),
    persistSession: true,
    autoRefreshToken: true,
  }
});